### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by randomaccess3** [woanware/usbdeviceforensics#1]
I've run into a problem using a windows 7 registry hive.
I haven't seen this error before but have attached a screenshot of the event log
Unfortunately I'm unable to provide a copy of the hives. 
![image](https://cloud.githubusercontent.com/assets/1241363/4229166/e1a4244a-3969-11e4-9184-242f85d14f31.jpg)

**Comment by woanware** [comment]
I am currently rewriting USBDeviceForensics as a python script so hopefully this won't be an issue
