### ISSUE TITLE
issue with date conversion in usbdeviceforensics.py

### ISSUE THREAD

**Issue by hydrocloricacid** [woanware/usbdeviceforensics#2]
The code (e.g. line 517) records the value of the registry entry not the the actual timestamp.
Which then causes errors later when it tries the print the date.

In the excerpt of code below my changes to fix the issue was to use g"key64.timestamp()" instead of "value64.value()"
e.g.  line 517
# usb_device.usbstor_datetime64 = value64.value()

usb_device.usbstor_datetime64 = key64.timestamp()

I have tested this and it works well. (there are few more of the same changes to make in the following lines of code)
I emailed your gmail account with my changed code. Tried using git to upload the changes but no access rights.

I noticed in the file I emailed to you that there are a few more of the same changes to make.

**Comment by hydrocloricacid** [comment]
Is there anything else I can do to help with getting this fix to be included in your code ?

**Comment by woanware** [comment]
Fixed in v0.0.3
