### ISSUE TITLE
Any plans for win10 support?

### ISSUE THREAD

**Issue by Rasmus-Riis** [woanware/usbdeviceforensics#7]
As the title reads.

It has changed a lot and doesn't work anymore

**Comment by woanware** [comment]
More information as to what the issues are is generally useful?

**Comment by Rasmus-Riis** [comment]
Wow that was fast 😊
For starters there is no USBSTOR.

I'm using the precompiled exe (v1.0.14).

It is quite old and doesn't have an option for win 10 in the drop down.

But as far as I can tell it's the latest.

Please correct me if I'm wrong

Br,
Rasmus




Rasmus Riis Kristensen
Sent from my Android

man. 8. okt. 2018 12.23 skrev Mark Woan <notifications@github.com>:

> More information as to what the issues are is generally useful?
>
> On Mon, 8 Oct 2018 at 11:21, Rasmus Riis Kristensen <

**Comment by woanware** [comment]
I have just realised that you are using the old .Net version, which has been superseded by the python script in this repo. The GUI is gone, it is now a console app/script
