### ISSUE TITLE
Error when building with cx_Freeze

### ISSUE THREAD

**Issue by esecrpm** [woanware/usbdeviceforensics#9]
I get the following error when building with cx_Freeze 5.1.1 on Python 2.7 (python registry is installed and usbdeviceforensics.py runs without issue)

C:\Python27\usbdeviceforensics-master>..\python.exe setup.py build
-----8<-----
Copying data from package Registry...
error: [Error 3] The system cannot find the path specified: 'C:\\Python27\\lib\\site-packages\\python_registry-1.3.1-py2.7.egg\\Registry\\*.*'

I can manually navigate to the egg file and read the contents.  Any ideas/suggestions on how to build Windows executable correctly?

**Comment by woanware** [comment]
For some reason cx_freeze isn't looking inside the .egg file.

So to compile, change the .egg file extension to zip, then unzip, and move
the contents to the following new directory:

site-packages\Registry

That directory should only contain the actual *.py files from the unzipped
directory e.g. Registry.py, RegistryLog.py, RegistryParse.py,
SettingsParse.py
